# Terraform-oci-test pipeline
# Yaml reference: https://aka.ms/yaml

# Trigger Push-Requests
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - README.md
      - azure-pipelines.yml
      - docs/*


# Trigger Pull-Requests
pr:
- main
- feature/*

strategy:
  matrix:
    mshosted:
      poolName: Azure Pipelines
      vmImage: ubuntu-latest
    selfhosted:
      poolname: Lurse Agents
      vmImage:

pool:
  name: $(poolName)
  vmImage: $(vmImage)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

